language: python
python:
    - 3.7
    - 3.8
before_intall:
    - python --version
    - pip install -U pip
    - pip install -U pytest
    - pip install codecov
    - pip install pytest-cov
install:
    - python -m pip install --upgrade pip
    - python -m pip install --upgrade setuptools
    - python -m pip install -r requirements.txt
    - python -m pip install .
script:
    - python -m pytest
after_success:
    - codecov