language: python
python:
    - "3.8"
install:
    - python -m pip install --upgrade pip
    - python -m pip install --upgrade setuptools
    - python -m pip install -r requirements.txt
    - python -m pip install .
script:
    - python -m pytest